### PR TITLE
Fixxed Copy/Paste error (Bug #8)

### PR DESCRIPTION
**Pull request by MrCryptoT**
Fixxed the filecopy bug (I believe cannot test it currently).
reason was a Copy&Paste bug i haven't noticed up to now...

### CODE REVIEW

**Comment by k-304** [comment]
Shoud I Merge this PR or not? Because you synced someting newer than thes here...

**Comment by MrCryptoT** [comment]
You can sync it... the other changes are not included in this PR (have to fully implement them first)

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: SnipeLike notifications@github.com 
Datum: 27.05.2015  14:47  (GMT+01:00) 
An: SnipeLike/WinBackupper WinBackupper@noreply.github.com 
Cc: Tom tom.harrison@hotmail.ch 
Betreff: Re: [WinBackupper] Fixxed Copy/Paste error (Bug #8) (#9) 

Shoud I Merge this PR or not? Because you synced someting newer than thes here...

**Comment by k-304** [comment]
Top, Merged

**Comment by MrCryptoT** [comment]
Thanks mate.Will call you when I made further changes

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: SnipeLike notifications@github.com 
Datum: 27.05.2015  15:07  (GMT+01:00) 
An: SnipeLike/WinBackupper WinBackupper@noreply.github.com 
Cc: Tom tom.harrison@hotmail.ch 
Betreff: Re: [WinBackupper] Fixxed Copy/Paste error (Bug #8) (#9) 

Top, Merged

**Pull request merged**
