### PR TITLE
Fixxed Updater Issue

### PR DESCRIPTION
**Pull request by MrCryptoT**
Updater Issue Fixxed - Should work now...
Still needs testing though.
Also I wrote the Loops to reach each file in a Sourcefolder which should be backed-up.
only the routine to copy it is missing . (writing it at a later point - kind of tired)
Futrhermore I have added a "StringToArray"-Function which will turn a String like "nr1;nr2;nr3" into Array like Array[nr1,n2,nr3] if called like "dim Array = StringToArray("nr1;nr2;nr3", ";")

Have fun reviewing the changed ;) :P
(And testing the update function. Also you could start testing if the loop realy reaches all files by putting out a message box with "filepath" as output... you will understand it when reading the code... search for "Copy/Backup" in form1.vb and you will be at the place I mean. And nice filename by the Way :P)

### CODE REVIEW

**Comment by k-304** [comment]
Thx m8, that sounds great!
Gonna take a look at it  now and testing it.

**Comment by MrCryptoT** [comment]
Perfect =)  (and no stress ;) )

**Comment by k-304** [comment]
UPDATE:
I added the version Control with "Assamly Information..." found in "project -> properties..."
This Version number there is also shown in "form1" automaticly (or automaticuly...?? don't knwo xD)
As soon as the form1 is loaded, it will write this Version number into a new XML File "version.xml".
(Needed here:)
I updated your "THC_Updater":
The Updater will read this XML File and save it in "localversnr1" , so this is the local version. I just changed in the "check for update" line localversnr to localversnr1. There is also a new BW to read the XML File if it exists.

**Comment by MrCryptoT** [comment]
Awesome - now you just shouldnt forget to update it there :P

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: SnipeLike notifications@github.com 
Datum: 17.05.2015  11:45  (GMT+01:00) 
An: SnipeLike/WinBackupper WinBackupper@noreply.github.com 
Cc: T0mH4rr1s0n tom.harrison@hotmail.ch 
Betreff: Re: [WinBackupper] Fixxed Updater Issue (#2) 

UPDATE:

I added the version Control with "Assamly Information..." found in "project -> properties..."

This Version number there is also shown in "form1" automaticly (or automaticuly...?? don't knwo xD)

As soon as the form1 is loaded, it will write this Version number into a new XML File "version.xml".

(Needed here:)

I updated your "THC_Updater":

The Updater will read this XML File and save it in "localversnr1" , so this is the local version. I just changed in the "check for update" line localversnr to localversnr1. There is also a new BW to read the XML File if it exists.

**Comment by MrCryptoT** [comment]
Hey - look at the following Icons - maybe you like one of them ...
(The first one would be from the same set of icons as my updater icon is)

http://www.google.ch/imgres?imgurl=http://www.veryicon.com/icon/ico/Folder/Leox%252520Graphite/Backup.ico&imgrefurl=http://www.veryicon.com/icons/folder/leox-graphite/backup-1.html&h=256&w=256&tbnid=HGNLqVwR-ULzmM:&zoom=1&docid=2jCYEc8vhIIIjM&ei=lNZZVaeCPYmssgHNuYAg&tbm=isch&ved=0CEQQMyggMCAhttp://www.google.ch/imgres?imgurl=http://www.veryicon.com/icon/ico/Application/Crystal%252520BW/Hdd.ico&imgrefurl=http://www.veryicon.com/icons/application/android/backup-7.html&h=256&w=256&tbnid=vWc0L_wODhh6XM:&zoom=1&docid=YYhmrJAUBkaQdM&ei=lNZZVaeCPYmssgHNuYAg&tbm=isch&ved=0CEAQMygcMBwhttp://www.google.ch/imgres?imgurl=http://www.iconsplace.com/download/white-data-backup-512.ico&imgrefurl=http://www.iconsplace.com/white-icons/data-backup-icon&h=512&w=512&tbnid=yvyk6Phpsl0lIM:&zoom=1&docid=mLZxXxuVt6RE2M&ei=lNZZVaeCPYmssgHNuYAg&tbm=isch&ved=0CC4QMygSMBI
http://www.google.ch/imgres?imgurl=http://www.iconarchive.com/download/i23108/laurent-baumann/blend/Drive-Backup.ico&imgrefurl=http://www.iconarchive.com/tag/backup-drive&h=256&w=256&tbnid=VMEN1FC3RbhNGM:&zoom=1&docid=OGaST8qmWEY5yM&ei=lNZZVaeCPYmssgHNuYAg&tbm=isch&ved=0CCEQMygFMAUhttp://www.google.ch/imgres?imgurl=http://www.iconarchive.com/download/i31944/thiago-silva/palm/Settings-Backup-Sync.ico&imgrefurl=http://www.iconarchive.com/tag/backup&h=256&w=256&tbnid=74KUgH1-CBsPZM:&zoom=1&docid=C0A1z48BpsAWTM&ei=lNZZVaeCPYmssgHNuYAg&tbm=isch&ved=0CCQQMygIMAg

Nur so nebed bii... 
Usserdem suech mal e Schriftfarb woder gfallt - wegem schwarze hintergrund söttemer die ja ändere... 
Ufruuume (duplciates lösche) tueni denn no =).

**Comment by k-304** [comment]
S erste Icon findi guet... 
mege de farbe... eif mal teste was guet uusgseht... ev wiis?

**Comment by MrCryptoT** [comment]
Musch nur es icon file anrhaue ^^ Farb ändere chani ned xD Isch glaub ide proj. Settings

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: SnipeLike notifications@github.com 
Datum: 18.05.2015  17:41  (GMT+01:00) 
An: SnipeLike/WinBackupper WinBackupper@noreply.github.com 
Cc: T0mH4rr1s0n tom.harrison@hotmail.ch 
Betreff: Re: [WinBackupper] Fixxed Updater Issue (#2) 

S erste Icon findi guet... 

mege de farbe... eif mal teste was guet uusgseht... ev wiis?

**Comment by k-304** [comment]
Ah easy ja den luegi das mal na ah wie das gaht..
dusch du hüt na de code und dateie uufrume? (ned das ich dir bim icon ine tue in weg chhume ;) )

**Comment by MrCryptoT** [comment]
I lueg dasi no dezue chum bis am 12i... :)

Von meinem Samsung Gerät gesendet.

-------- Ursprüngliche Nachricht --------
Von: SnipeLike notifications@github.com 
Datum: 18.05.2015  18:22  (GMT+01:00) 
An: SnipeLike/WinBackupper WinBackupper@noreply.github.com 
Cc: T0mH4rr1s0n tom.harrison@hotmail.ch 
Betreff: Re: [WinBackupper] Fixxed Updater Issue (#2) 

Ah easy ja den luegi das mal na ah wie das gaht..

dusch du hüt na de code und dateie uufrume? (ned das ich dir bim icon ine tue in weg chhume ;) )

**Pull request merged**
